# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodname', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.day')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routineapp.period')),
            ],
        ),
    ]
