# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routineapp', '0002_auto_20170924_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
