# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineapp', '0003_auto_20170924_0610'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='subject',
            order_with_respect_to='day',
        ),
    ]
