# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-24 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routineapp', '0004_auto_20170924_0632'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='day',
            new_name='days',
        ),
        migrations.RenameModel(
            old_name='period',
            new_name='periods',
        ),
    ]
